### ISSUE TITLE
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user

### ISSUE THREAD

**Issue by Herzogdb** [LaunchKit/LaunchKit#9]
I'm not sure at what point this stops working...but the warnings say it will be removed in a future release.

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default).
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

**Comment by kaustubhn** [comment]
Also got similar error

CMD OUTPUT
/LaunchKit $ vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default).
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ERROR! Unexpected Exception: name 'urllib2' is not defined
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.


Any help to solve this would be appreciated.
Thanks

**Comment by taylorhughes** [comment]
@kaustubhn yours is different. can you show the output of `ansible` and `pip --version` from your command line?

**Comment by kaustubhn** [comment]
$ ansible --version
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides

$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by brentrobbins** [comment]
I got further with setting it up ($ vagrant up --provision), however Ansible failed with the following error message:
```
TASK [postgres : add local user as postgres superuser] *************************
fatal: [default]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @ansible/vagrant.retry

PLAY RECAP *********************************************************************
default                    : ok=17   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by taylorhughes** [comment]
@brentrobbins this appears unrelated, can you try `vagrant destroy` -> yes, then `vagrant provision --up` again and see if things finish?

**Comment by brentrobbins** [comment]
@taylorhughes Same error. I thought it might be related since the error mentioned something about permissions.

**Comment by taylorhughes** [comment]
@brentrobbins what's your `ansible --version` ?

**Comment by taylorhughes** [comment]
@brentrobbins what's your `ansible --version` ?

**Comment by brentrobbins** [comment]
@taylorhughes It's 2.1.1.0

**Comment by taylorhughes** [comment]
@brentrobbins did you try a destroy/re-provision? I just reprovisioned successfully with same version of ansible.

**Comment by brentrobbins** [comment]
@taylorhughes Destroy first. I ran: `$ vagrant destroy' and then  `$ vagrant up --provision` screenshot: http://jmp.sh/n6X8VwZ

**Comment by yanokwa** [comment]
On a fresh install with Vagrant 1.8.5 and Ansible 2.1.1.0, I'm also having this problem. My quick fix has been to set "allow_world_readable_tmpfiles = True" in ~/.ansible.cfg and that seems to be the recommended workaround. https://github.com/ansible/ansible/issues/16048

**Comment by Ranjitha112** [comment]
when i run my ansible playbook am getting below error can anyone help me please

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
ERROR! 'checksum' is not a valid attribute for a Task

**Comment by jarce6791** [comment]
I have this issue:
==> default: [DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
==> default: make sure become_method is 'sudo' (default).
==> default: This feature will be removed in a 
==> default: future release. Deprecation warnings can be disabled by setting 
==> default: deprecation_warnings=False in ansible.cfg.

And after this show this issue:
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Please I need help with this
